### ISSUE TITLE
How does this extention be loaded?

### ISSUE THREAD

**Issue by zoumi** [Yggdroot/LeaderF-changes#1]
I found that there is no .vim file in autoload directory, so I have to copy the content of ./plugin/leaderf-changes.vim to my vimrc?

**Comment by Yggdroot** [comment]
No, just `Plug 'Yggdroot/LeaderF-changes'` if you are using [vim-plug](https://github.com/junegunn/vim-plug).

**Comment by zoumi** [comment]
Thanks. I found I forgot put it to g:Lf_SelfContent.
This works:
```
command! -bar -nargs=0 LeaderfChanges Leaderf changes 
let g:Lf_SelfContent['LeaderfChanges'] = "vim change list"
```
